pipeline {
    agent {
        kubernetes {
            yaml '''
                apiVersion: v1
                kind: Pod
                metadata:
                  name: centos
                spec:
                  containers:
                  - name: centos
                    image: centos
                    command:
                    - sleep
                    args:
                    - 99d
                  restartPolicy: Never
            '''
        }
    }
    stages {
        stage('Deploy') {
            steps {
                git 'https://github.com/samuelomonedo247/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
                sh '''
                    cd Chapter08/sample1
                    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                    chmod +x ./kubectl
                    ./kubectl apply -f calculator.yaml -n staging
                    ./kubectl apply -f hazelcast.yaml -n staging
                '''
            }
        }
        stage('Rolling Upgrade') {
            when {
                changeset '*/calculator.yaml'
                changeset '*/hazelcast.yaml'
            }
            agent {
                kubernetes {
                    yaml '''
                        apiVersion: v1
                        kind: Pod
                        metadata:
                          name: centos
                        spec:
                          containers:
                          - name: centos
                            image: centos
                            command:
                            - sleep
                            args:
                            - 99d
                          restartPolicy: Never
                    '''
                }
            }
            steps {
                sh '''
                    cd Chapter06/sample5
                    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                    chmod +x ./kubectl
                    ./kubectl rollout restart deployment/calculator -n staging
                    ./kubectl rollout restart deployment/hazelcast -n staging
                '''
            }
        }
    }
}
